export const ADD_STAFFS = "ADD_STAFFS";
export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FALSE";
export const ADD_DEPARTMENTS = "ADD_DEPARTMENTS";
export const DEPARTMENTS_LOADING = "DEPARTMENTS_LOADING";
export const DEPARTMENTS_FAILED = "DEPARTMENTS_FALSE";
export const ADD_STAFF = "ADD_STAFF";
export const SPLICE_STAFF = "SPLICE_STAFF";
